### ISSUE TITLE
switch verb and context in commands

### ISSUE THREAD

**Issue by timvink** [ing-bank/doing-cli#27]
Now we have the verb first:

```shell
doing create issue
doing create pr
doing close pr
doing close issue
doing list
doing init
doing open issue
doing open pr
```

Probably a subset of `doing` users also use / are used to the [github cli](https://cli.github.com/manual), which has the other order, f.e.:

```shell
gh issue create
gh issue close
gh issue list
gh pr ...
```

It's a more natural grouping of the commands, and I've notice in using `doing` that I actually already typed `doing issue create` once, probably because I first think of the thing I want to manipulate (issue) before what I want to do with it (create). It mainly applies to creating and closing, not so much the others.

Concretely, do:

- Implement `doing issue create`, `doing issue close`, `doing pr create` and `doing pr close`
-  `doing create issue`, `doing close issue`, `doing create pr` and `doing close pr`
    - Write deprecation messages (print alternative + warn deprecation in v1)
    - Hide those commands from the `--help` output (https://click.palletsprojects.com/en/7.x/api/#commands)
    - Remove from documentation

**Comment by operte** [comment]
I find that the `<verb> <item>` makes more sense, but it feels mostly a matter of convention. To make adopting `doing` as easy as possible, we can change it to the `<item> <verb>` syntax, sure :) 

The only advantage of the `<verb> <item> <item_no>` syntax that I see is that maybe in the future we could find a way to skip the `<item>` and just have `<verb> <item_no>` automatically figure out what type of `<item>` `<item_no>` relates to. That might be a bit more awkward to achieve on the `<item> <verb> <item_no>` syntax.
