### ISSUE TITLE
`create pr` creates branch even if it already exists

### ISSUE THREAD

**Issue by operte** [ing-bank/doing-cli#30]
Not sure if it is a bug or an enhancement, but when `doing create pr <issue_id>`, `doing` creates a new branch, even if one already existed. 

In my particular case, I had created a branch using the UI, and then it created another with `doing create pr -d -c <issue_id>`.  They have different names. I don't know if the same would have happened if in the UI I had created a branch with exactly the name that `doing` would have used.

**Comment by timvink** [comment]
It's a feature, not a bug. Some people have multiple PRs for the same issue.

https://github.com/timvink/doing-cli/blob/9580e5ab3abc3ead97c744bf68ff6bee0cc7194f/src/doing/create/pr.py#L59-L67

However, if you want to use doing to create multiple PRs for the same issue, you cannot currently. We could add a `branch_name` option, f.e. `doing create pr <issue_id> --branch_name '<issue_id>_<a branch name>'`. But not sure if it's a common enough workflow to facilitate this. I'm inclined to keep it simple until a user takes the effort to post an issue for this one.

**Comment by operte** [comment]
Oh, I see, so the problem was that I had already created a branch for that PR but it did not follow the naming convention from `doing-cli`. 

I agree that probably the most common workflow is to have one branch per issue. In this case, I would find it useful if there was also a warning indicating that there is already a branch connected to the issue, even if it doesn't follow the `doing-cli` naming convention. The user would then be asked if the new branch should still be created or not.

I think this might be useful if you created a branch on the UI but forgot about it, for example. What do you think?

**Comment by timvink** [comment]
Yeah the additional print output with others PRs connected to the same issue would be helpful.

Prompts get annoying quick, better to assume the user knows what he/she is doing. It's also easy to clean up if you do make a 'mistake'.
