### ISSUE TITLE
pr create: Provide more helpful error message when you do not have access to a repository

### ISSUE THREAD

**Issue by PaulHofma** [ing-bank/doing-cli#43]
Currently, when trying to create PR for a repository to which you do not have contributor rights, we get an empty error message. Took me a little bit of rummaging about on my own before I could find out what the problem was. The `azure cli` actually does provide a useful error message here (telling us we don't have access), so perhaps a possible solution would be to forward the azure error message if any pop up?

**Comment by timvink** [comment]
I'm having trouble reproducing this one. I assume this is a situation where you have viewing rights but not contributing rights. Probably what is happening is that the error message is communicated via `stdout` instead of `stderr`. I made error handling code a bit more robust for this:

https://github.com/ing-bank/doing-cli/commit/d2c10dfae3bbac2a68c365965c5810eb6d4fd1a5#diff-04186dccbae3e4068b23960111707533a0a45468dbd51a2000fd9a83ee46f6fdR170-R171

Will release shortly, then you can try and see if this fixes it.

**Comment by PaulHofma** [comment]
Hmm this didn't quite do it, it would appear. I do believe it is exactly the situation which you describe (can view but can't contribute).

Actual error message (I've only copied the last bit since pasting the provided error messages doesn't work great, sadly, due to the formatting):

| /usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site │
│ -packages/doing/pr/create_pr.py:113 in cmd_create_pr                                             │
│                                                                                                  │
│   110 │   │   cmd = f"az repos ref create --name 'heads/{branch_name}' --repository '{repo_nam   │
│   111 │   │   cmd += f"--object-id '{master_branch_object_id}' -p '{project}' --org '{organiza   │
│   112 │   │   branch = run_command(cmd)                                                          │
│ ❱ 113 │   │   assert branch.get("success")                                                       │
│   114 │   │   console.print(f"[dark_orange3]>[/dark_orange3] Created remote branch '[cyan]{bra   │
│   115 │                                                                                          │
│   116 │   # Create the PR
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError:

So interestingly enough, I think the issue is that the function itself doesn't error out - it only gives an info message. Then the branch.get assert fails, as we couldn't actually create the branch.

**Comment by timvink** [comment]
Thanks for this! I should have added a helpful error message there, which I did now:

https://github.com/ing-bank/doing-cli/blob/df135f04a51dfb7978a3ebf6c439f587dc744ad6/src/doing/pr/create_pr.py#L115

Will be released in `v1.1` in a bit. Thanks for reporting this stuff, really helps make `doing` better!
