### ISSUE TITLE
Add `--type` argument to `doing list` 

### ISSUE THREAD

**Issue by operte** [ing-bank/doing-cli#60]
This would be quite handy. For example, I want to create a bug under a user story, but my `doing list` is quite long, so it is hard to find what's the appropriate parent code for my bug.

I'll make time to work on this :)

**Comment by timvink** [comment]
Nice addition, that indeed should be there. 

You can re-use the option from `doing issue create`

https://github.com/ing-bank/doing-cli/blob/4ef61031f153e700a9609f0216c6ffc374a3d3ec/src/doing/issue/commands.py#L73-L81

Let me know if need some pointers

**Comment by timvink** [comment]
Released in [v1.2.1](https://github.com/ing-bank/doing-cli/releases/tag/v1.2.1)
