### ISSUE TITLE
On a thin terminal window, `ID` and `PRs` columns should not be shrunk

### ISSUE THREAD

**Issue by operte** [ing-bank/doing-cli#69]
If the terminal window is too thin, the column widths are shrunk. However that should not be possible for `ID` and `PRs`, since that's the most important information. 

Example: 
![image](https://user-images.githubusercontent.com/4223965/123390875-b0ee8180-d59b-11eb-95ad-3a506056fd85.png)

Perhaps there's a way of disabling dynamic width for specific columns.

**Comment by timvink** [comment]
We now specify the rich columns as a string, but could can also use `rich.table.Column` which has two parameters we can experiment with: `overflow` and `min_width` (https://rich.readthedocs.io/en/latest/reference/table.html#rich.table.Column). The latter seems most promising.
