### ISSUE TITLE
ValueErrors on some workitems

### ISSUE THREAD

**Issue by MHeus** [ing-bank/doing-cli#70]
On a `doing list` the following error was returned due to missing milliseconds in the time data string:

`   ValueError: time data '2021-07-13T08:56:40Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'`

This is caused by line 139 in `_list.py`:
`    item_datetime = datetime.datetime.strptime(item_datetime, "%Y-%m-%dT%H:%M:%S.%fZ`

When testing with the `.%f` removed from that line, a similar error occurred on another work item:

`    ValueError: time data '2021-06-08T08:15:17.547Z' does not match format '%Y-%m-%dT%H:%M:%SZ'`

So apparently some Work Items are returned with and some without milliseconds....

The following code fix solved the issue:

```
        try:
            item_datetime = datetime.datetime.strptime(item_datetime, "%Y-%m-%dT%H:%M:%S.%fZ")
        except ValueError:
            item_datetime = datetime.datetime.strptime(item_datetime, "%Y-%m-%dT%H:%M:%SZ")
```

**Comment by timvink** [comment]
Nice catch! Thanks for reporting. Would you like to provide a PR?

**Comment by MHeus** [comment]
Of course, I have a branch ready to pushed once authorized.

**Comment by timvink** [comment]
No need to authorize, you can create a fork , commit and push there, and create then a pull request ([guide](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)).
