### ISSUE TITLE
`doing open board` doesn't show the right iteration

### ISSUE THREAD

**Issue by operte** [ing-bank/doing-cli#92]
`doing open board` is simply opening the team board without filtering on area nor iteration.

**Comment by operte** [comment]
In a related issue, `doing open sprint` also doesn't filter the correct Area. This is important when the multiple smaller teams are sharing the same Team and the same Sprint, and the only thing differentiating tasks is the Area.

**Comment by timvink** [comment]
> doing open board is simply opening the team board without filtering on area nor iteration.

If I remember correctly azure devops had no way of specifying this in the URL. Still implemented it because it still saved me time navigating the UI.

**Comment by timvink** [comment]
Looks like there's been some work in this area done by the azure devops teams: https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/filter-backlogs-boards-plans?view=azure-devops

**Comment by operte** [comment]
I think you are right, it is not possible to pass filters on the Azure Boards pages using the URI. That's unfortunate. I will close this issue.
