### ISSUE TITLE
Repository in One Project While Boards is In Another

### ISSUE THREAD

**Issue by sheldonhull** [ing-bank/doing-cli#96]
Using the azure cli directly I've not had much of an issue, as it can autodetect the repo details from the `.git` details. However, using doing I realized I had an issue as it expects the project & repo to be in the same project. 

This might be atypical, but I since an org can have many projects and the repos can be linked to work-items in another project, is there some way to get the tool to autodetect the repository to create the PR against, while still allowing PR creation in the repository project?

**Comment by operte** [comment]
Hmm that's an interesting one. doing was designed to solve a specific problem at our company: we share a single project with every team. So, exactly the opposite situation that you have.

In principle this should be possible, but I can imagine there are a couple of places where there might be problems to sort out. Can you tell us where you are finding issues?

Just to be sure: your repo and boards are in different projects, but you only use one board project. Is this right?

**Comment by operte** [comment]
Hey @sheldonhull, did you have a chance to look at my previous questions?

**Comment by operte** [comment]
I'll close this issue for lack of further information.
